html = open('index.html').read()

# Find and remove the entire old EXAMPLES object
import re
start = html.find('const EXAMPLES = {')
end = html.find('};', start) + 2
old_examples = html[start:end]

new_examples = """const EXAMPLES = {
  balter: { brand:'Balter Brewing', category:'FMCG / Food & Drink', audience:'Australian craft beer drinkers 25-40 who championed Balter before the buyout and now feel conflicted', ambition:'Challenge a cultural norm', brief:"Balter was founded by pro surfers who made genuinely great beer. Then Carlton United Breweries bought them. Now they have the distribution to be everywhere but the credibility that made people love them is under threat. How do you scale without selling out — or do you lean into the contradiction?", tone:'Raw & honest' },
  moccona: { brand:'Moccona', category:'FMCG / Food & Drink', audience:'Australians 35-60 who grew up with Moccona on the bench but have quietly moved on to pods or cafe coffee', ambition:'Reposition a brand', brief:"Moccona was Australia's idea of sophisticated coffee for 50 years. Then the world got complicated — pods, single origin, cold brew, oat milk flat whites. We need to find Moccona's place in a coffee culture it no longer leads — without apologising for what it is.", tone:'Raw & honest' },
  qantas: { brand:'Qantas', category:'Travel & Tourism', audience:'Australians who fly regularly but have lost faith in the airline after years of poor service', ambition:'Reposition a brand', brief:"Qantas used to be a source of national pride. Now it's a punchline. Australians feel betrayed — by cancelled flights, lost baggage, and a CEO who became a villain. We need to begin rebuilding trust without pretending nothing happened.", tone:'Raw & honest' },
  guinness: { brand:'Guinness', category:'FMCG / Food & Drink', audience:'Australian beer drinkers 25-45 who see Guinness as a special occasion drink, not an everyday pint', ambition:'Drive brand fame', brief:"Guinness is one of the world's most iconic brands but younger drinkers see it as their dad's pint. We need to show that waiting for a Guinness isn't just acceptable — it's a virtue.", tone:'Cinematic & epic' },
  up: { brand:'Up Bank', category:'Finance / Banking', audience:'Australians 18-35 who hate their bank but have never heard of anything better', ambition:'Drive brand fame', brief:"Up Bank is Melbourne-born, genuinely beautifully designed, and beloved by everyone who uses it. The problem: almost nobody knows it exists. It has grown entirely on word of mouth. How do you scale awareness without losing the thing that made word of mouth work in the first place?", tone:'Bold & provocative' },
  hj: { brand:"Hungry Jack's", category:'FMCG / Food & Drink', audience:"Australians 16-35 who eat fast food regularly but default to McDonald's out of habit", ambition:'Challenge a cultural norm', brief:"Everyone knows the burgers are better at Hungry Jack's. The product is genuinely superior. The price is competitive. And yet McDonald's dominates. Australians choose the golden arches on autopilot. How do you break a habit that has nothing to do with quality and everything to do with familiarity?", tone:'Bold & provocative' },
  mg: { brand:'MG Motor', category:'Automotive', audience:"Australians who bought an MG because the value was undeniable but feel slightly embarrassed to admit it", ambition:'Drive brand fame', brief:"MG is selling more cars in Australia than anyone predicted. Australians are buying them rationally — the spec is great, the price is unbeatable. But nobody is proud to own one. Nobody puts an MG sticker on their laptop. How do you build genuine brand love for a car people chose with their head, not their heart?", tone:'Bold & provocative' },
  aesop: { brand:'Aesop', category:'Health & Wellness', audience:'Design-conscious Australians 25-45 who see Aesop as a marker of good taste but struggle to justify the price', ambition:'Drive brand fame', brief:"Aesop is one of the most distinctive brands in the world — every store, every product, every word is considered. But its reputation for pretension alienates as many people as it attracts. We need to make Aesop feel genuinely warm and human without losing the intellectual rigour that makes it special.", tone:'Minimalist & pure' },
  ringers: { brand:'Ringers Western', category:'Fashion / Retail', audience:'Both working rural Australians and urban 18-35s who romanticise country life', ambition:'Challenge a cultural norm', brief:"Ringers Western makes gear for people who actually work the land. But it's increasingly being worn by city kids who romanticise that life. Do you lean into authentic rural roots and risk losing the growing urban audience? Or embrace the crossover and risk alienating the core who made you?", tone:'Raw & honest' },
  kitkat: { brand:'KitKat', category:'FMCG / Food & Drink', audience:'Global audience of adults 18-35 who are chronically overworked and permanently online', ambition:'Drive brand fame', brief:"Have a Break has been one of advertising's most enduring ideas. But in a world where people are more burnt out than ever yet unable to actually stop, the idea of a break feels either more relevant or completely impossible. We need to make KitKat the brand that gives people genuine permission to stop — in a world that never does.", tone:'Witty & playful' },
  stan: { brand:'Stan', category:'Entertainment', audience:"Australians 25-45 who have Stan but feel vaguely embarrassed when someone asks what they watch", ambition:'Reposition a brand', brief:"Stan is Australia's homegrown streaming service. It's been around since 2015, has decent content, and millions of subscribers. But it feels like the streaming service you turn to when you've exhausted everything else. Netflix is prestige. Disney+ is family. Stan is... there. How do you make Stan feel like a first choice, not a fallback?", tone:'Bold & provocative' },
  nrl: { brand:'NRL', category:'Entertainment', audience:'Australians in Melbourne, Adelaide and Perth who follow AFL but have never given rugby league a chance', ambition:'Challenge a cultural norm', brief:"The NRL is the biggest sport in Queensland and NSW but it feels like someone else's game south of the border. The product is fast, brutal and genuinely exciting. But in Melbourne it may as well be a foreign sport. How do you make the NRL feel like it belongs to all Australians, not just the ones above the Barassi Line?", tone:'Bold & provocative' },
  specsavers: { brand:'Specsavers', category:'Health & Wellness', audience:"Australians 25-50 who go to Specsavers because it's cheap but would never describe themselves as a Specsavers person", ambition:'Reposition a brand', brief:"Specsavers owns Australian optical retail on price. Should've Gone to Specsavers is one of the most recognised taglines in the country. But eyewear has become fashion — brands like Oscar Wylee are making glasses feel aspirational. Specsavers needs to evolve from the place you go because it's affordable to the place you go because it's genuinely good.", tone:'Witty & playful' },
  canva: { brand:'Canva', category:'Technology', audience:'Designers and marketers who use Canva daily but feel slightly guilty admitting it', ambition:'Drive brand fame', brief:"Canva started as a scrappy startup that democratised design and made the establishment uncomfortable. Now it's worth 40 billion dollars and used by 170 million people. The thing that made people love Canva — that it felt like it was on your side — is under threat as it scales into enterprise software. How do you grow to global dominance without losing the underdog spirit that got you there?", tone:'Bold & provocative' },
  woodstock: { brand:'Woodstock Bourbon', category:'FMCG / Food & Drink', audience:'Australians 25-45 who drink Woodstock without thinking but could not tell you why they love it', ambition:'Drive brand fame', brief:"Woodstock just launched their biggest brand campaign in years. Australia noticed. But does one campaign change 40 years of being the bourbon you drink without thinking? The creative problem is not awareness — it is identity. How do you turn Australia's most habitual drink into Australia's most loved one?", tone:'Warm & human' }
};"""

html = html.replace(old_examples, new_examples)
open('index.html', 'w').write(html)
print('Done — examples rebuilt')
