import re

html = open('index.html').read()

# Find and replace the entire EXAMPLES object
start = html.find('const EXAMPLES = {')
end = html.find('};', start) + 2

new_examples = """const EXAMPLES = {
  balter: { brand:'Balter Brewing', audience:'Australian craft beer drinkers 25-40 who championed Balter before the CUB buyout and now feel conflicted', ambition:'Challenge a cultural norm', brief:"Balter was founded by pro surfers Mick Fanning and Joel Parkinson with one mission: good beer is for everybody. They built something real — fun, inclusive, unpretentious. Then Carlton United Breweries bought them. Now they're everywhere, which was the point, but some of the faithful feel betrayed. The brand voice is larrikin without being a dickhead about it — casual, self-aware, never takes itself too seriously. Ideas should feel like something you'd say over a beer, not in a boardroom. The creative challenge: how do you scale without selling out — or do you lean into the contradiction with the same honesty that made people love Balter in the first place?", tone:'Raw & honest' },
  moccona: { brand:'Moccona', audience:'Australians 35-60 who grew up with Moccona on the bench but have quietly moved on to pods or cafe coffee', ambition:'Reposition a brand', brief:"Moccona was Australia's idea of sophisticated coffee for 50 years — that distinctive jar was a status symbol on the kitchen bench. Then the world got complicated. Pods arrived. Third wave cafes arrived. The jar started looking daggy. Moccona's tone has always been warm, considered, slightly European — unhurried, never shouty. It should never try to be a young brand. The creative challenge: find Moccona's place in a coffee culture it no longer leads, without apologising for what it is. There's something powerful in a brand that knows exactly what it is and refuses to pretend otherwise.", tone:'Warm & human' },
  qantas: { brand:'Qantas', audience:'Australians who fly regularly but have lost faith in the airline after years of cancelled flights, lost baggage and a CEO who became a villain', ambition:'Reposition a brand', brief:"Qantas used to make Australians feel proud. The Flying Kangaroo was ours — something we pointed at and said 'that's us.' Then came the pandemic, then came Alan Joyce, then came the Senate inquiry. Australians feel genuinely betrayed. The brand has historically been warm, patriotic, cinematic — the 'I Still Call Australia Home' school of advertising. But that register feels tone-deaf right now. The creative challenge: begin rebuilding trust without pretending nothing happened. Earned humility, not manufactured warmth. This is a brand that needs to listen before it speaks.", tone:'Raw & honest' },
  guinness: { brand:'Guinness', audience:'Australian beer drinkers 25-45 who see Guinness as a special occasion pint, not an everyday drink', ambition:'Drive brand fame', brief:"Guinness is one of the world's most mythologised brands. It moves slowly, deliberately, quietly — like the pour itself. The brand tone is cinematic and philosophical. It finds meaning in ordinary things. It never shouts. It speaks to people who value character over convenience. The 119.5 seconds of the perfect pour isn't a problem — it's the entire point. Younger Australians see Guinness as their dad's pint, something you order at an Irish pub on St Patrick's Day. The creative challenge: show that waiting for a Guinness isn't just acceptable — it's a virtue. In a world engineered for instant everything, the man who waits has already won.", tone:'Cinematic & epic' },
  up: { brand:'Up Bank', audience:'Australians 18-35 who hate their bank but have never heard of anything better', ambition:'Drive brand fame', brief:"Up Bank is Melbourne-born, built by engineers who were sick of bad banking apps. The product is genuinely world-class — beautiful design, real-time spending insights, no fees. The tone is digital-native, warm, occasionally cheeky — it talks like a friend, not a financial institution. Up has grown almost entirely on word of mouth. The problem: most Australians have never heard of it. The creative challenge: scale awareness without losing the thing that made word of mouth work. Up's magic is that it feels like it's on your side — which is radical in a category designed to confuse you. Don't lose that.", tone:'Bold & provocative' },
  hj: { brand:"Hungry Jack's", audience:'Australians 16-35 who eat fast food regularly but default to McDonalds out of habit', ambition:'Challenge a cultural norm', brief:"Everyone knows the burgers are better at Hungry Jack's. This isn't opinion — it's practically a national truth. The Whopper is objectively a better burger than the Big Mac. And yet McDonald's dominates. Hungry Jack's tone has always been a bit larrikin, a bit challenger — it's never pretended to be premium, it just claims to be better. The creative challenge: break a habit that has nothing to do with quality and everything to do with familiarity. People choose McDonald's on autopilot. The golden arches have become a default, not a decision. How do you make people actually think?", tone:'Bold & provocative' },
  mg: { brand:'MG Motor', audience:"Australians who bought an MG because the value was undeniable but feel slightly embarrassed to admit it", ambition:'Drive brand fame', brief:"MG is selling more cars in Australia than anyone predicted. The spec is genuinely impressive. The price is unbeatable. But nobody is proud to own one — nobody puts an MG sticker on their laptop or mentions it at a dinner party. It's a rational purchase people make and then quietly justify. The brand has almost no emotional identity in Australia. The creative challenge: build genuine brand love for a car people chose with their head, not their heart. You can't make people proud of something they already own by just making ads — you have to give them a real reason to believe.", tone:'Bold & provocative' },
  aesop: { brand:'Aesop', audience:'Design-conscious Australians 25-45 who see Aesop as a marker of good taste but struggle to justify the price', ambition:'Drive brand fame', brief:"Aesop is one of the most distinctive brands ever created. Every detail is considered — the amber bottles, the apothecary labels, the store design, the literary tone of every piece of copy. The brand communicates through restraint. It whispers where others shout. It quotes Camus on product packaging. It treats customers as intellectuals, not consumers. No celebrities. No discounts. No promises of eternal youth. Aesop's reputation for being slightly pretentious is both its greatest asset and its only vulnerability. The creative challenge: make Aesop feel genuinely warm and human without losing the intellectual rigour that makes it extraordinary. Ideas should feel like they were written by someone who reads.", tone:'Minimalist & pure' },
  ringers: { brand:'Ringers Western', audience:'Both working rural Australians and urban 18-35s who romanticise country life', ambition:'Challenge a cultural norm', brief:"Ringers Western makes gear for people who actually work the land — jackets, boots, hats built for real conditions. But it's increasingly being discovered by city kids who romanticise country life and want to look the part. The brand voice is direct, no-bullshit, authentically Australian — it doesn't wink at the camera or play up the rural cliché. It just means it. The creative challenge: navigate the tension between authentic rural heritage and a growing urban audience without alienating either. Lean too hard into the bush and you lose the city. Go too lifestyle and you lose the people who actually muster cattle. The answer probably lives somewhere in genuine respect for both.", tone:'Raw & honest' },
  kitkat: { brand:'KitKat', audience:'Global audience of adults 18-35 who are chronically overworked and permanently online', ambition:'Drive brand fame', brief:"Have a Break has been one of advertising's most enduring ideas — simple, human, true. But the world it was made for no longer exists. Australians work longer hours than almost any developed nation. They eat lunch at their desks. They check Slack at 11pm. The idea of a break has never been more needed — or more impossible. KitKat's tone is playful but never silly. It's knowing, a bit witty, always warm. It doesn't lecture. The creative challenge: make KitKat the brand that gives people genuine permission to stop — in a world that never does. Not just a chocolate bar you eat without thinking. A cultural position on rest that feels radical because it should be obvious.", tone:'Witty & playful' },
  stan: { brand:'Stan', audience:"Australians 25-45 who have Stan but feel vaguely embarrassed when someone asks what they watch", ambition:'Reposition a brand', brief:"Stan is Australia's homegrown streaming service. It has millions of subscribers and genuinely good content. But it occupies an awkward cultural position — nobody leads with Stan. Netflix is prestige. Disney+ is family. Binge is HBO. Stan is... there. It's the streaming service you recommend apologetically: 'it's actually pretty good.' The brand has historically been functional rather than cultural. The creative challenge: make Stan feel like a first choice, not a fallback. Australians should be proud to recommend Stan the way they're proud to recommend a good local restaurant. The answer probably isn't about content — it's about making Stan feel like it belongs to Australia in a way no other service can claim.", tone:'Bold & provocative' },
  nrl: { brand:'NRL', audience:'Australians in Melbourne, Adelaide and Perth who follow AFL but have never given rugby league a chance', ambition:'Challenge a cultural norm', brief:"The NRL is the biggest sport in Queensland and NSW — fast, brutal, genuinely spectacular. But south of the Barassi Line it may as well be a foreign language. In Melbourne, AFL is everything. The NRL feels like someone else's game, someone else's culture. The brand tone for this challenge needs to be confident but not arrogant — it can't alienate AFL fans by attacking the code they love. The creative challenge: make the NRL feel like it belongs to all Australians, not just the ones above the border. There's probably something powerful in the fact that rugby league doesn't care if you like it — it's been there your whole life whether you noticed or not.", tone:'Bold & provocative' },
  specsavers: { brand:'Specsavers', audience:"Australians 25-50 who go to Specsavers because it's the sensible choice but would never describe themselves as a Specsavers person", ambition:'Reposition a brand', brief:"Should've Gone to Specsavers is one of the most famous taglines in Australian advertising — self-deprecating, funny, memorable. Specsavers built dominance on price and accessibility. But eyewear has become fashion. Oscar Wylee, Bailey Nelson, Ollie Quinn are making glasses feel like a design choice. Specsavers' tone has always been warm and approachable with a dry sense of humour. The creative challenge: evolve from the brand people go to because it's affordable to the brand people go to because it's genuinely good. The price advantage is real — but the perception needs to catch up with the reality that Specsavers actually makes excellent eyewear.", tone:'Witty & playful' },
  canva: { brand:'Canva', audience:'Designers and marketers who use Canva daily but feel slightly guilty admitting it to people who use the Adobe suite', ambition:'Drive brand fame', brief:"Canva started as a scrappy Melbourne startup with a simple idea: design shouldn't require a design degree. It democratised an entire industry and made the establishment uncomfortable. Now it's worth $40 billion and used by 170 million people. The brand tone is warm, optimistic, democratising — it believes everyone has something to say and should be able to say it beautifully. But as Canva scales into enterprise and competes with Microsoft and Google, the scrappy underdog spirit is under threat. The creative challenge: grow to global dominance without losing the thing that made people love Canva — that it felt like it was on your side against the establishment.", tone:'Bold & provocative' },
  woodstock: { brand:'Woodstock Bourbon', audience:'Australians 25-45 who drink Woodstock without thinking but could not tell you a single thing about the brand', ambition:'Drive brand fame', brief:"Woodstock has been in Australian fridges since 1980. It's the bourbon at every footy club, every house party, every regional pub. Nobody talks about it. Everyone drinks it. It wins on habit and availability, not aspiration. Woodstock just launched their biggest brand campaign in years — Australia noticed. But does one campaign change 40 years of being the bourbon you drink without thinking? The brand tone should be laconic, honest, unpretentious — the complete opposite of the American bourbon playbook with its heritage mythology and distillery reverence. Woodstock is just a good drink that doesn't need to be more than that. The creative challenge: turn Australia's most habitual drink into Australia's most loved one, without making it something it's not.", tone:'Warm & human' }
};"""

html = html[:start] + new_examples + html[end:]
open('index.html', 'w').write(html)
print('Done — all 15 briefs updated with brand DNA')
